package com.campuslostfound;
import com.campuslostfound.db.DatabaseManager; import com.campuslostfound.exception.ValidationException; import com.campuslostfound.model.*; import com.campuslostfound.service.*; import com.campuslostfound.util.*; import java.sql.*; import java.time.LocalDate; import java.util.*;
public class Main {
 private final Scanner s=new Scanner(System.in); private final UserService users=new UserService(); private final ItemService items=new ItemService(users); private final MatchingService matcher=new MatchingService(); private final ClaimService claims=new ClaimService(items,users); private final CsvExporter exporter=new CsvExporter();
 public static void main(String[]a){try{DatabaseManager.initialize();new Main().run();}catch(SQLException e){System.out.println("Database startup error: "+e.getMessage());}}
 private void run(){System.out.println("\n==========================================\n   CAMPUS LOST & FOUND MANAGEMENT\n==========================================");boolean go=true;while(go){menu();try{int c=InputValidator.readInt(s,"Enter choice: ");switch(c){case 1->register();case 2->viewStudents();case 3->report("LOST");case 4->report("FOUND");case 5->viewItems("LOST");case 6->viewItems("FOUND");case 7->search();case 8->matches();case 9->claim();case 10->viewClaims();case 11->updateClaim();case 12->backup();case 0->go=false;default->System.out.println("Choose a valid option.");}}catch(ValidationException|SQLException e){System.out.println("[Error] "+e.getMessage());}}s.close();System.out.println("Goodbye!");}
 private void menu(){System.out.println("\n1. Register Student\n2. View Students\n3. Report Lost Item\n4. Report Found Item\n5. View Lost Items\n6. View Found Items\n7. Search Items\n8. Find Possible Matches\n9. Submit Claim\n10. View Claims\n11. Update Claim Status\n12. Backup Items (background thread)\n0. Exit");}
 private void register()throws SQLException,ValidationException{int id=users.addStudent(InputValidator.readRequired(s,"Name: "),InputValidator.readRequired(s,"Email: "),InputValidator.readRequired(s,"Student ID: "));System.out.println("Student registered with ID: "+id);}
 private void viewStudents()throws SQLException{List<Student>a=users.getStudents();if(a.isEmpty())System.out.println("No students.");else a.forEach(System.out::println);}
 private void report(String type)throws SQLException,ValidationException{int uid=InputValidator.readInt(s,"Student user ID: ");String title=InputValidator.readRequired(s,"Item title: ");ItemCategory cat=InputValidator.readCategory(s);String loc=InputValidator.readRequired(s,"Location: ");LocalDate d=InputValidator.readDate(s,"Date");String desc=InputValidator.readRequired(s,"Description: ");System.out.println(type+" item recorded with ID: "+items.addItem(uid,type,title,cat,loc,d,desc));}
 private void viewItems(String type)throws SQLException{List<Item>a=items.getItems(type);if(a.isEmpty())System.out.println("No records.");else for(Item i:a)System.out.println(i.summary()+" | "+i.getDescription());}
 private void search()throws SQLException,ValidationException{List<Item>a=items.search(InputValidator.readRequired(s,"Keyword: "));if(a.isEmpty())System.out.println("No matches.");else a.forEach(i->System.out.println(i.summary()));}
 private void matches()throws SQLException{List<MatchingService.MatchResult>a=matcher.findMatches(items.getItems("LOST"),items.getItems("FOUND"));if(a.isEmpty())System.out.println("No possible matches above 50%.");else for(var m:a)System.out.println("Lost #"+m.lost().getId()+" ("+m.lost().getTitle()+") <-> Found #"+m.found().getId()+" ("+m.found().getTitle()+") | Score: "+m.score()+"%");}
 private void claim()throws SQLException,ValidationException{int id=InputValidator.readInt(s,"Found item ID: ");int uid=InputValidator.readInt(s,"Your user ID: ");String msg=InputValidator.readRequired(s,"Why is this yours? ");System.out.println("Claim created with ID: "+claims.addClaim(id,uid,msg));}
 private void viewClaims()throws SQLException{List<String>a=claims.getClaims();if(a.isEmpty())System.out.println("No claims.");else a.forEach(System.out::println);}
 private void updateClaim()throws SQLException,ValidationException{int id=InputValidator.readInt(s,"Claim ID: ");int n=InputValidator.readInt(s,"1-PENDING 2-APPROVED 3-REJECTED: ");if(n<1||n>3)throw new ValidationException("Invalid status.");claims.updateStatus(id,ClaimStatus.values()[n-1]);System.out.println("Claim updated.");}
 private void backup(){new BackupService(exporter).start();System.out.println("Backup started in background.");}
}
