package com.campuslostfound.db;
import java.nio.file.*; import java.sql.*;
public class DatabaseManager {
 private static final String URL="jdbc:h2:./data/campus_lost_found";
 public static Connection getConnection() throws SQLException { try{Files.createDirectories(Path.of("data"));}catch(Exception e){throw new SQLException("Unable to create data directory",e);} return DriverManager.getConnection(URL,"sa",""); }
 public static void initialize() throws SQLException {
  String u="CREATE TABLE IF NOT EXISTS users(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,role VARCHAR(20) NOT NULL,student_id VARCHAR(50))";
  String i="CREATE TABLE IF NOT EXISTS items(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INT NOT NULL,type VARCHAR(10) NOT NULL,title VARCHAR(150) NOT NULL,category VARCHAR(30) NOT NULL,location VARCHAR(150) NOT NULL,item_date DATE NOT NULL,description VARCHAR(500),status VARCHAR(20) NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id))";
  String c="CREATE TABLE IF NOT EXISTS claims(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,item_id INT NOT NULL,claimant_id INT NOT NULL,message VARCHAR(500),status VARCHAR(20) NOT NULL,FOREIGN KEY(item_id) REFERENCES items(id),FOREIGN KEY(claimant_id) REFERENCES users(id))";
  try(Connection c1=getConnection(); Statement s=c1.createStatement()){s.execute(u);s.execute(i);s.execute(c);}
 }
}
